export const ROUTES = {
  LOGIN: '/login',
  SIGNUP: '/signup',
  ONBOARDING: '/onboarding',
  DASHBOARD: '/dashboard',
  DASHBOARD_CONTENT: '/dashboard/content',
  DASHBOARD_CONTENT_DETAIL: '/dashboard/content/:id',
  DASHBOARD_API_KEYS: '/dashboard/api-keys',
  DASHBOARD_POLICIES: '/dashboard/policies',
  DASHBOARD_POLICY_EDIT: '/dashboard/policies/:id/edit',
  DASHBOARD_ANALYTICS: '/dashboard/analytics',
  DASHBOARD_WEBHOOKS: '/dashboard/webhooks',
  DASHBOARD_TEAM: '/dashboard/team',
  DASHBOARD_BILLING: '/dashboard/billing',
  MODERATOR: '/moderator',
  MODERATOR_REVIEW: '/moderator/review/:id',
  MODERATOR_STATS: '/moderator/stats',
  ADMIN: '/admin',
  ADMIN_ORGS: '/admin/organizations',
  ADMIN_ORG_DETAIL: '/admin/organizations/:id',
  ADMIN_ANALYTICS: '/admin/analytics',
} as const;
