export const ROUTES = {
  LOGIN: '/login',
  SIGNUP: '/signup',
  ONBOARDING: '/onboarding',
  DASHBOARD: '/dashboard',
  DASHBOARD_CONTENT: '/dashboard/content',
  DASHBOARD_CONTENT_DETAIL: '/dashboard/content/:id',
  DASHBOARD_ANALYTICS: '/dashboard/analytics',
  MODERATOR: '/moderator',
  MODERATOR_REVIEW: '/moderator/review/:id',
  MODERATOR_STATS: '/moderator/stats',
  ADMIN: '/admin',
  ADMIN_ORGS: '/admin/organizations',
  ADMIN_ORG_DETAIL: '/admin/organizations/:id',
  ADMIN_ANALYTICS: '/admin/analytics',
} as const;
